INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Batido', 3800.00, 'BATIDOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Batido Nesquik', 4200.00, 'BATIDOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Smoothie', 4100.00, 'BATIDOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Sundae Go', 3700.00, 'BATIDOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Agua 2lt', 2000.00, 'BEBIDAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Agua 500ml', 1000.00, 'BEBIDAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Baggio', 800.00, 'BEBIDAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Gaseosa 1.5lt', 0.00, 'BEBIDAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Gaseosa 500ml', 2000.00, 'BEBIDAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Lata', 1700.00, 'BEBIDAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Block 110gr', 4200.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Block 170gr', 7000.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Block 300gr', 10800.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Block 38gr', 1400.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Cofler 55gr', 2700.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Cofler Tofi/Bon', 800.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Gelatinas', 700.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Graffiti 45gr', 1500.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Maní c/Choco', 1100.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Roclets 40gr', 1400.00, 'CHOCOLATES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('1 Bocha', 2400.00, 'CUCURUCHOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('2 Bochas', 3100.00, 'CUCURUCHOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('3 Bochas', 3400.00, 'CUCURUCHOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('GRIDO 2 Bochas', 3300.00, 'CUCURUCHOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('GRIDO 3 Bochas', 3700.00, 'CUCURUCHOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Super Gridito', 2500.00, 'CUCURUCHOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Baño de Chocolate', 600.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Bengala Brillo', 1000.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Bengala Común', 600.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Blister x3', 1000.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Salsita 15gr', 550.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Topping x1', 550.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Topping x2', 1000.00, 'EXTRAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Familiar nro 1', 14500.00, 'FAMILIARES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Familiar nro 2', 14500.00, 'FAMILIARES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Familiar nro 3', 14500.00, 'FAMILIARES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Familiar nro 4', 14500.00, 'FAMILIARES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('1 kg', 13500.00, 'GRANEL', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('1/2 kg', 7800.00, 'GRANEL', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('1/4 kg', 4500.00, 'GRANEL', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Bombón x1', 1000.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Bombón x10', 7000.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Bombón x20', 14000.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Cremoso x1', 900.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Cremoso x10', 5500.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Cremoso x20', 11000.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Frutal x1', 800.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Frutal x10', 5000.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Palito Frutal x20', 10000.00, 'PALITOS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Bastones', 5300.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Empanadas', 7800.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Mini Pizza', 3100.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Pechugas', 5300.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Pizza Casera', 8200.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Pizza Cebolla', 5800.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Pizza Jamón', 6200.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Pizza Mozzarella', 5800.00, 'PIZZAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Alfajor Secreto x 1', 2200.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Alfajor Secreto x 6', 12500.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Almendrado x 8', 9500.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Almendrado x1', 1600.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Cassatta x 1', 1600.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Cassatta x 8', 9500.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Crocante x 1', 1600.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Crocante x 8', 11000.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Crocantino', 9500.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Delicias', 9500.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Escocés x 1', 1800.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Escocés x 8', 12500.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Frutezza x 1', 1600.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Frutezza x 8', 11000.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Suizo x 1', 1700.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Suizo x 8', 12000.00, 'POSTRES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('2 Bocha TOY', 4100.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('2 de 1/4', 8500.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('2 de 2 Bochas', 6000.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('2 Escocés', 23000.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('2 Kilos', 25000.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('3x2 Alm o Cas', 19000.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('kg + medio', 19800.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Kilo Reutilizable', 22500.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Recarga Kilo', 12200.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Recarga Medio kilo', 7000.00, 'PROMOCIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Helado s/Az', 2600.00, 'SIN TACC', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Postre Veg', 2600.00, 'SIN TACC', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Yogurt', 2600.00, 'SIN TACC', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Chocolate', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Crema Americana', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Crema Cookie', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Dulce de Leche', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Dulce de Leche Granizado', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Frutilla', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Granizado', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Limón', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Menta Granizado', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Vainilla', 7500.00, 'TENTACIONES', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Torta Frutilla', 14000.00, 'TORTAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Torta Grido', 14000.00, 'TORTAS', true);
INSERT INTO productos (nombre, precio_unitario, categoria, activo) VALUES ('Torta Oreo', 14000.00, 'TORTAS', true);